# Generated by Django 4.2.4 on 2023-10-21 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_expenses_amount_alter_registration_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
