# Generated by Django 4.2.4 on 2023-10-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_renewal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='renewal',
            name='days',
            field=models.DateField(blank=True, null=True),
        ),
    ]
