# Generated by Django 4.2.4 on 2023-09-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_expenses_registration_renewal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Trash', 'Trash'), ('Terminate', 'Terminate')], default='Active', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='purpose',
            field=models.CharField(choices=[('Domain Registration', 'Domain Registration'), ('Domain Renewal', 'Domain Renewal'), ('Hosting Registration', 'Hosting Registration'), ('Hosting Renewal', 'Hosting Renewal')], max_length=50),
        ),
    ]
