# Generated by Django 4.2.4 on 2023-10-21 06:35

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_aboutpage_homepage_pricingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
